/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ventana;
import controlador.Controller;

/**
 *
 * @author josez
 */
public class AprendeSumarJuego extends javax.swing.JFrame {

    Inicio miI = null;
    Controller c = new Controller();
    /**
     * Creates new form NewJFrame
     */
    public AprendeSumarJuego(Inicio miI) {
        initComponents();
        labelBad.setVisible(false);
        labelNice.setVisible(false);
        this.miI = miI;
        asignarValoresLables();
        asignarValoresBotones();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        numero1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        numero2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        labelNice = new javax.swing.JLabel();
        labelBad = new javax.swing.JLabel();
        btnOpcion1 = new javax.swing.JButton();
        btnOpcion2 = new javax.swing.JButton();
        btnOpcion3 = new javax.swing.JButton();
        btnOpcion4 = new javax.swing.JButton();
        btnComoJugar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Goudy Stout", 0, 24)); // NOI18N
        jLabel2.setText("Sumate");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 230, 190, 50));

        numero1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        numero1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        numero1.setText("320");
        getContentPane().add(numero1, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 350, 60, 40));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel3.setText("-------------");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 430, 170, 10));

        numero2.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        numero2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        numero2.setText("320");
        getContentPane().add(numero2, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 390, 60, 40));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel5.setText("+");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 370, 40, 40));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel6.setText("?");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 450, 20, 40));

        labelNice.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/nice.jpg"))); // NOI18N
        labelNice.setText("jLabel4");
        getContentPane().add(labelNice, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 310, 210, 210));

        labelBad.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/bad.jpg"))); // NOI18N
        getContentPane().add(labelBad, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 320, -1, -1));

        btnOpcion1.setBackground(new java.awt.Color(204, 204, 204));
        btnOpcion1.setFont(new java.awt.Font("Goudy Stout", 0, 14)); // NOI18N
        btnOpcion1.setText("123");
        btnOpcion1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOpcion1ActionPerformed(evt);
            }
        });
        getContentPane().add(btnOpcion1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 540, 110, 40));

        btnOpcion2.setBackground(new java.awt.Color(204, 204, 204));
        btnOpcion2.setFont(new java.awt.Font("Goudy Stout", 0, 14)); // NOI18N
        btnOpcion2.setText("999");
        btnOpcion2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOpcion2ActionPerformed(evt);
            }
        });
        getContentPane().add(btnOpcion2, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 540, 110, 40));

        btnOpcion3.setBackground(new java.awt.Color(204, 204, 204));
        btnOpcion3.setFont(new java.awt.Font("Goudy Stout", 0, 14)); // NOI18N
        btnOpcion3.setText("878");
        btnOpcion3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOpcion3ActionPerformed(evt);
            }
        });
        getContentPane().add(btnOpcion3, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 540, 110, 40));

        btnOpcion4.setBackground(new java.awt.Color(204, 204, 204));
        btnOpcion4.setFont(new java.awt.Font("Goudy Stout", 0, 14)); // NOI18N
        btnOpcion4.setText("658");
        btnOpcion4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOpcion4ActionPerformed(evt);
            }
        });
        getContentPane().add(btnOpcion4, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 540, 110, 40));

        btnComoJugar.setBackground(new java.awt.Color(204, 204, 204));
        btnComoJugar.setFont(new java.awt.Font("Goudy Stout", 0, 14)); // NOI18N
        btnComoJugar.setText("Inicio");
        btnComoJugar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnComoJugarActionPerformed(evt);
            }
        });
        getContentPane().add(btnComoJugar, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 600, 150, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/colorful-background-with-funny-children-vector.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 970, 946));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnOpcion4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOpcion4ActionPerformed
 
    }//GEN-LAST:event_btnOpcion4ActionPerformed

    private void btnOpcion1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOpcion1ActionPerformed
    
    }//GEN-LAST:event_btnOpcion1ActionPerformed

    private void btnOpcion2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOpcion2ActionPerformed

    }//GEN-LAST:event_btnOpcion2ActionPerformed

    private void btnOpcion3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOpcion3ActionPerformed
  
    }//GEN-LAST:event_btnOpcion3ActionPerformed

    private void btnComoJugarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnComoJugarActionPerformed
        
        miI.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnComoJugarActionPerformed

    public void asignarValoresLables(){
        numero1.setText(""+c.generarNumeros());
        numero2.setText(""+c.generarNumeros());
    }
    
    public void asignarValoresBotones(){
        int asignador = c.generarAsignador();
        
        if(asignador == 0){
            btnOpcion1.setText(""+(Integer.parseInt(numero1.getText())+Integer.parseInt(numero2.getText())));
        }else{
            btnOpcion2.setText(""+c.generarNumeros());
        }
        if(asignador == 1){
            btnOpcion2.setText(""+(Integer.parseInt(numero1.getText())+Integer.parseInt(numero2.getText())));
        }else{
            btnOpcion2.setText(""+c.generarNumeros());
        }
        if(asignador == 2){
            btnOpcion3.setText(""+(Integer.parseInt(numero1.getText())+Integer.parseInt(numero2.getText())));
        }else{
            btnOpcion3.setText(""+c.generarNumeros());
        }
        if(asignador == 3){
            btnOpcion4.setText(""+(Integer.parseInt(numero1.getText())+Integer.parseInt(numero2.getText())));
        }else{
            btnOpcion4.setText(""+c.generarNumeros());
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnComoJugar;
    private javax.swing.JButton btnOpcion1;
    private javax.swing.JButton btnOpcion2;
    private javax.swing.JButton btnOpcion3;
    private javax.swing.JButton btnOpcion4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel labelBad;
    private javax.swing.JLabel labelNice;
    private javax.swing.JLabel numero1;
    private javax.swing.JLabel numero2;
    // End of variables declaration//GEN-END:variables
}
