/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ventana;

/**
 *
 * @author josez
 */
public class ComoSumar extends javax.swing.JFrame {

    int auxPaso = 0;
    Inicio miI = null;
    /**
     * Creates new form ComoSumar
     */
    public ComoSumar(Inicio miI) {
        
        this.miI = miI;
        
        initComponents();
        lblr1.setVisible(false);
        lblr2.setVisible(false);
        lblr3.setVisible(false);
        lblCarreo.setVisible(false);
        lblSumExtra.setVisible(false);
        btnAnterior.setVisible(false);
        lblPaso2.setVisible(false);
        lblPaso2_2.setVisible(false);
        lblPaso2Suma.setVisible(false);
        lblPaso3.setVisible(false);
        lblPaso3Suma.setVisible(false);
        lblPaso3_1.setVisible(false);
        lblPaso3_2.setVisible(false);
        lblPaso3_3.setVisible(false);
        lblPaso4.setVisible(false);
        lblPaso4suma.setVisible(false);
        lblPaso4_2.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblComoSumar = new javax.swing.JLabel();
        lblPaso2Suma = new javax.swing.JLabel();
        lblPaso2 = new javax.swing.JLabel();
        lblPaso2_2 = new javax.swing.JLabel();
        lblPaso3 = new javax.swing.JLabel();
        lblPaso3Suma = new javax.swing.JLabel();
        lblPaso3_1 = new javax.swing.JLabel();
        lblPaso3_2 = new javax.swing.JLabel();
        lblPaso3_3 = new javax.swing.JLabel();
        lblPaso4 = new javax.swing.JLabel();
        lblPaso4suma = new javax.swing.JLabel();
        lblPaso4_2 = new javax.swing.JLabel();
        lblSumExtra = new javax.swing.JLabel();
        lblnumero1 = new javax.swing.JLabel();
        lblnumero2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblCarreo = new javax.swing.JLabel();
        lblr1 = new javax.swing.JLabel();
        lblr2 = new javax.swing.JLabel();
        lblr3 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        btnAnterior = new javax.swing.JButton();
        btnSiguiente = new javax.swing.JButton();
        lblInterrogante = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblComoSumar.setFont(new java.awt.Font("Goudy Stout", 0, 24)); // NOI18N
        lblComoSumar.setText("¿COMO SUMAR?");
        getContentPane().add(lblComoSumar, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 370, 370, 50));

        lblPaso2Suma.setFont(new java.awt.Font("Britannic Bold", 0, 14)); // NOI18N
        lblPaso2Suma.setText("3+5 = 8");
        getContentPane().add(lblPaso2Suma, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 290, 50, 20));

        lblPaso2.setFont(new java.awt.Font("Britannic Bold", 0, 14)); // NOI18N
        lblPaso2.setText("Para empezar sumamos los dos numero que se encuentran mas a la derecha,");
        getContentPane().add(lblPaso2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 240, 490, 30));

        lblPaso2_2.setFont(new java.awt.Font("Britannic Bold", 0, 14)); // NOI18N
        lblPaso2_2.setText("En este caso tenemos el 3 y el 5, Recuerda inciar siempre por la derecha.");
        getContentPane().add(lblPaso2_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 260, 490, 30));

        lblPaso3.setFont(new java.awt.Font("Britannic Bold", 0, 14)); // NOI18N
        lblPaso3.setText("Luego tomamos los vecinos de la izquierda de los numero anteriores, como vemos son el 7 y el 8.");
        getContentPane().add(lblPaso3, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 320, 630, 20));

        lblPaso3Suma.setFont(new java.awt.Font("Britannic Bold", 0, 14)); // NOI18N
        lblPaso3Suma.setText("7+8 = 15");
        getContentPane().add(lblPaso3Suma, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 340, 60, 20));

        lblPaso3_1.setFont(new java.awt.Font("Britannic Bold", 0, 14)); // NOI18N
        lblPaso3_1.setText("Pero espera, no podemos poner un numero de 2 cifras hasta el final de la suma, por lo tanto ");
        getContentPane().add(lblPaso3_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 360, 620, 20));

        lblPaso3_2.setFont(new java.awt.Font("Britannic Bold", 0, 14)); // NOI18N
        lblPaso3_2.setText("solo tomamos el numero de la derecha de nuestro resultado y lo ponemos debajo de la linea (El 5).");
        getContentPane().add(lblPaso3_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 380, 630, 20));

        lblPaso3_3.setFont(new java.awt.Font("Britannic Bold", 0, 14)); // NOI18N
        lblPaso3_3.setText("Pero ¿y el numero de la izquiera?, ese 1 restante se lo prestamos al vecino de la izquierda y se lo sumamos.");
        getContentPane().add(lblPaso3_3, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 400, 690, 20));

        lblPaso4.setFont(new java.awt.Font("Britannic Bold", 0, 14)); // NOI18N
        lblPaso4.setText("Finalmente tomamos el 9 y el 3.");
        getContentPane().add(lblPaso4, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 430, 210, 20));

        lblPaso4suma.setFont(new java.awt.Font("Britannic Bold", 0, 14)); // NOI18N
        lblPaso4suma.setText("9+3 = 12");
        getContentPane().add(lblPaso4suma, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 450, 60, 20));

        lblPaso4_2.setFont(new java.awt.Font("Britannic Bold", 0, 14)); // NOI18N
        lblPaso4_2.setText("Como no hay ningun vecino a la izquierda al que le podamos prestar el 1, ponemos las 2 cifras en el resultado.");
        getContentPane().add(lblPaso4_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 470, 740, -1));

        lblSumExtra.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lblSumExtra.setText("+");
        getContentPane().add(lblSumExtra, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 480, 30, 40));

        lblnumero1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        lblnumero1.setText("873");
        getContentPane().add(lblnumero1, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 500, 60, 40));

        lblnumero2.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        lblnumero2.setText("385");
        getContentPane().add(lblnumero2, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 540, 60, 40));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel3.setText("-------------");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 580, 170, 10));

        lblCarreo.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lblCarreo.setText("1");
        getContentPane().add(lblCarreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 470, 20, 40));

        lblr1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        lblr1.setText("8");
        getContentPane().add(lblr1, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 590, 20, 40));

        lblr2.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        lblr2.setText("5");
        getContentPane().add(lblr2, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 590, 20, 40));

        lblr3.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        lblr3.setText("12");
        getContentPane().add(lblr3, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 590, -1, 40));

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel10.setText("+");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 520, 30, 40));

        btnAnterior.setBackground(new java.awt.Color(204, 204, 204));
        btnAnterior.setFont(new java.awt.Font("Goudy Stout", 0, 10)); // NOI18N
        btnAnterior.setText("Anterior");
        btnAnterior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnteriorActionPerformed(evt);
            }
        });
        getContentPane().add(btnAnterior, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 650, 140, 40));

        btnSiguiente.setBackground(new java.awt.Color(204, 204, 204));
        btnSiguiente.setFont(new java.awt.Font("Goudy Stout", 0, 10)); // NOI18N
        btnSiguiente.setText("Iniciar");
        btnSiguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSiguienteActionPerformed(evt);
            }
        });
        getContentPane().add(btnSiguiente, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 650, 140, 40));

        lblInterrogante.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        lblInterrogante.setText("?");
        getContentPane().add(lblInterrogante, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 590, 30, 40));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/colorful-background-with-funny-children-vector.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 980, 970));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAnteriorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnteriorActionPerformed
        if(auxPaso == 1){
            btnSiguiente.setText("INICIAR");
            lblComoSumar.setVisible(true);
            lblInterrogante.setVisible(true);
            lblr1.setVisible(false);
            lblPaso2.setVisible(false);
            lblPaso2_2.setVisible(false);
            lblPaso2Suma.setVisible(false);
            btnAnterior.setVisible(false);
            
        }
        if(auxPaso == 2){
            lblPaso3.setVisible(false);
            lblPaso3Suma.setVisible(false);
            lblPaso3_1.setVisible(false);
            lblPaso3_2.setVisible(false);
            lblr2.setVisible(false);
            
        }
         if(auxPaso == 3){
            lblPaso3_3.setVisible(false);
            lblCarreo.setVisible(false);
            lblSumExtra.setVisible(false);
        }
         if(auxPaso == 4){
            lblnumero1.setText("873");
            lblCarreo.setVisible(true);
            lblSumExtra.setVisible(true);
         }
          if(auxPaso == 5){
            lblPaso4.setVisible(false);
            lblPaso4_2.setVisible(false);
            lblPaso4suma.setVisible(false);
            lblr3.setVisible(false);
            btnSiguiente.setText("SIGUIENTE");
        }
        auxPaso --;
    }//GEN-LAST:event_btnAnteriorActionPerformed

    private void btnSiguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSiguienteActionPerformed
        if(auxPaso == 0){
            btnSiguiente.setText("SIGUIENTE");
            lblInterrogante.setVisible(false);
            lblComoSumar.setVisible(false);
            lblr1.setVisible(true);
            lblPaso2.setVisible(true);
            lblPaso2_2.setVisible(true);
            lblPaso2Suma.setVisible(true);
            btnAnterior.setVisible(true);
            
        }
        if(auxPaso == 1){
            lblPaso3.setVisible(true);
            lblPaso3Suma.setVisible(true);
            lblPaso3_1.setVisible(true);
            lblPaso3_2.setVisible(true);
            lblr2.setVisible(true);
        }
        if(auxPaso == 2){
            lblPaso3_3.setVisible(true);
            lblCarreo.setVisible(true);
            lblSumExtra.setVisible(true);
        }
        if(auxPaso == 3){
            lblnumero1.setText("973");
            lblCarreo.setVisible(false);
            lblSumExtra.setVisible(false);
        }
        if(auxPaso == 4){
            lblPaso4.setVisible(true);
            lblPaso4_2.setVisible(true);
            lblPaso4suma.setVisible(true);
            lblr3.setVisible(true);
            btnSiguiente.setText("Terminar");
        }
        
        if(auxPaso == 5){
            miI.setVisible(true);
            this.dispose();
        }
        auxPaso ++;
    }//GEN-LAST:event_btnSiguienteActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAnterior;
    private javax.swing.JButton btnSiguiente;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel lblCarreo;
    private javax.swing.JLabel lblComoSumar;
    private javax.swing.JLabel lblInterrogante;
    private javax.swing.JLabel lblPaso2;
    private javax.swing.JLabel lblPaso2Suma;
    private javax.swing.JLabel lblPaso2_2;
    private javax.swing.JLabel lblPaso3;
    private javax.swing.JLabel lblPaso3Suma;
    private javax.swing.JLabel lblPaso3_1;
    private javax.swing.JLabel lblPaso3_2;
    private javax.swing.JLabel lblPaso3_3;
    private javax.swing.JLabel lblPaso4;
    private javax.swing.JLabel lblPaso4_2;
    private javax.swing.JLabel lblPaso4suma;
    private javax.swing.JLabel lblSumExtra;
    private javax.swing.JLabel lblnumero1;
    private javax.swing.JLabel lblnumero2;
    private javax.swing.JLabel lblr1;
    private javax.swing.JLabel lblr2;
    private javax.swing.JLabel lblr3;
    // End of variables declaration//GEN-END:variables
}
